### ISSUE TITLE
Re-entering the same song causes volume to increase

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#10]
Windows 10 x64, 0ea558b x64

Recording volume reduced by -6db.
This is only triggered by re-entering the song after leaving, and not by the restart button. It also appears to persist between different songs (as in playing a different song and coming back will still cause the volume increase).

https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/804cab19-f0b5-4084-b079-ad72a5fae549

**Comment by 3drosalia** [comment]
wahoo! solved in 52a615a
