### ISSUE TITLE
Notes became misaligned when window size is changed

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#12]
Windows 10 x64, 0ea558b x64

https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/3f022168-45a2-45fd-bcf9-7f74b3f25d83

**Comment by 3drosalia** [comment]
I have a pending commit on my system that should fix this issue, although itll probably take a bit for me to commit it as it needs some cleaning up.

**Comment by 3drosalia** [comment]
Also fixed recently within the last 6 commits on Indev.
