### ISSUE TITLE
Media keys trigger Overdrive

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#13]
Windows 10 x64, 0ea558b x64

Volume Up/Down, Mute, Play/Pause, Stop, Skip Forward, and Skip Back (all the media keys on my keyboard) activate Overdrive.

lol

https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/36dbc5cb-4fc3-46a4-8779-a222c1875be5

**Comment by 3drosalia** [comment]
what the absolute fuck

**Comment by cameron44251** [comment]
HUH same here

**Comment by 3drosalia** [comment]
Fixed in commit e60d14c
https://github.com/Encore-Developers/Encore-Raylib/assets/43187285/992fb4bd-904a-4fea-8bb7-fc7502004b15

**Comment by BraqueDown** [comment]
Still occurring in fa20278.

**Comment by 3drosalia** [comment]
You might need to open your binds file and change -1 to -2 anywhere you see it
-2 is the "not binded" key, -1 is the "unknown" key and is what media keys are binded to in glfw

**Comment by BraqueDown** [comment]
ah, I see.

**Comment by 3drosalia** [comment]
I will also note, pressing Unbind Key will set it to -1 in versions prior to 9e7461f
