### ISSUE TITLE
Overdrive depletes too quickly

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#15]
Windows 10 x64, fa20278 x64

Now lasts one measure instead of two.

https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/a4ee87bc-42d0-4449-93bb-93ac9f75ca13

**Comment by 3drosalia** [comment]
i know the exact issue and now i eliminated it, check 03c1ca0 as i reverted the OD code to be based on a set number rather than whatever math i was doing for midi resolution

**Comment by 3drosalia** [comment]
for some reason the math is weird, and the od code still needs to be changed to be based on the BEAT track, but setting it to how it was in older builds is better than what i was doing previously
