### ISSUE TITLE
Songs lower on list become unselectable when vertical resolution is too high.

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#7]
Windows 10 x64, 13dbb84 x64

I have a 1440p monitor, and I can't scroll all the way down the song list. When reducing the window height, more rows become visible.

The list is scrolled all the way down in all of these screenshots. Window width doesn't seem to affect the number of rows shown.

***H: 1408px***
---
![Screenshot 2024-05-19 13-29-14](https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/d472a694-d5ae-4a87-bac2-e7640fa23501)

***H: 1048px***
---
![Screenshot 2024-05-19 13-46-36](https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/4e2443ae-cce0-4067-8f3c-ef81f7dde64b)

***H: 688px***
---
![Screenshot 2024-05-19 13-48-37](https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/ecc2aa70-f9ed-4b68-bde7-ca24feec002a)

**Comment by 3drosalia** [comment]
Happened to be redoing menus, and saw this
Quickly went to fix this issue, but it'll be in the next commit on the song-select branch, so Actions wont automatically build the fix.
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/43187285/529d69d6-f29b-4cb8-beed-30fa702b5271)
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/43187285/4c25b2f5-4733-448d-905e-d5299453c327)
![image](https://github.com/Encore-Developers/Encore-Raylib/assets/43187285/acd876eb-9a43-4f13-bd94-3a8758dbec72)

**Comment by BraqueDown** [comment]
No longer occurs (more or less) in 0ea558b. The bottom row appears to be _ever so slightly_ shorter; presumably because it's obscured by the buttons.

![image](https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/2df4d6e4-f2da-484d-b5a7-759ec6d29513)

But everything is accessible now, which is what matters.
