### ISSUE TITLE
Lift notes can be hit through other notes in the same lane

### ISSUE THREAD

**Issue by BraqueDown** [Encore-Developers/Encore-Raylib#8]
Pretty self-explanatory. Song is 170 BPM and the snare roll is 16th note triplets, if it helps.

https://github.com/Encore-Developers/Encore-Raylib/assets/43602802/c52594bc-6388-4676-978d-eb95eed7d7a7

**Comment by kimicake** [comment]
holy moly

**Comment by BraqueDown** [comment]
No longer occurs in 0ea558b.
